name: Terraform Test Channel Normalization

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  test_channel_normalization:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0  # Coloque a versão do Terraform que você deseja usar

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Get Normalized Channel Output
        run: |
          echo "Normalized Channel: $(terraform output -raw normalized_channel)"
     
      - name: Convert and load variables
        run: |
            # Converte o arquivo customizado para um formato padrão `.env`
            sed -n 's/.*\(channel_raw =\|channel_no_space =\|channel_normalized =\|CHANNEL =\|SERVER =\|PATH_STARTEAM =\|PATH_DIST =\) *"//p' tes.env | sed 's/"//g' > simplified.env
            
            # Carrega as variáveis convertidas
            set -o allexport
            source ./simplified.env
            set +o allexport
              
      - name: Print loaded variables
        run: |
            echo "CHANNEL: $CHANNEL"
            echo "SERVER: $SERVER"
            echo "PATH_STARTEAM: $PATH_STARTEAM"
            echo "PATH_DIST: $PATH_DIST"
