name: Terraform Test Channel Normalization

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  test_channel_normalization:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0  # Coloque a versão do Terraform que você deseja usar

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Get Normalized Channel Output
        run: |
          echo "Normalized Channel: $(terraform output -raw normalized_channel)"
      
      - name: Load Environment Variables
        run: |
          set -a
          source ./test.env
          cat test.env
      
      - name: Set up environment variables
        run: |
              source test.env
              echo "CHANNEL=$CHANNEL"
              echo "channel_no_space=$channel_no_space"
              echo "channel_normalized=$channel_normalized 
              
      - name: Validate environment variables
        run: |
          source test.env
          if [ "$channel_normalized" != "nucleodeservicos" ]; then
              echo "Validation failed: channel_normalized is not as expected"
              exit 1
          fi
          echo "Validation passed: channel_normalized is as expected"