name: Install StarTeam Client

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Update packages
      run: sudo apt-get update --fix-missing

    - name: Install telnet and ssh
      run: sudo apt-get install -y telnet openssh-client
        
    


    #- name: Configure StarTeam for Git
    #  run: |
    #    export STARTEAM_HOME=/path/to/extract
    #    export PATH=$STARTEAM_HOME/bin:$PATH
    #    echo "export STARTEAM_HOME=/path/to/extract" >> $GITHUB_ENV
    #    echo "export PATH=$STARTEAM_HOME/bin:$PATH" >> $GITHUB_ENV
#
    #- name: Verify StarTeam installation
    #  run: |
    #    starteam --version
#
    #- name: Clone StarTeam repository
    #  run: |
    #    git clone starteam://path/to/repo
#
    
    #- name: Set up StarTeam Git Client
    #  run: |
    #    # Baixe o instalador do StarTeam Cross-Platform Client
    #    wget https://admhelp.microfocus.com/starteam/en/latest/online/Content/Install-Guide/Installing%20StarTeam%20Cross-Platform%20Client.html -O starteam-integrations.tar.gz
    #    
  
    #-ame: Set up StarTeam CLI
    #  run: |
    #   echo "Installing StarTeam CLI"
    #   sudo apt-get update
    #   sudo apt-get install -y stcmd # Ajuste conforme necessário para o CLI do StarTeam
#
    #- name: The migration
    #  id: migrate
    #  env:
    #    BB_REPO_URL: https://${{ vars.MIGRATION_BB_USER }}:${{ secrets.MIGRATION_BB_PASSWORD }}@bitbucket.bradesco.com.br:8443/scm/${{ steps.inputs.outputs.PROJECT_KEY }}/${{ steps.inputs.outputs.BITBUCKET_REPOSITORY }}.git
    #    MIGRATION_SOURCE: ${{ vars.MIGRATION_SOURCE }}
    #    STARTEAM_URL_BASE: ${{ secrets.MIGRATION_STARTEAM }}
    #  run: |
    #    echo "::group::Migration log"
    #    if [[ -n "${MIGRATION_SOURCE}" ]]; then
    #     printf "\e[0;33m%s\e[0m\n" "Adding remote for GitLab with URL ${MIGRATION_SOURCE}"
    #     git remote add bitbucket "${MIGRATION_SOURCE}"
    #     git config credential."${MIGRATION_SOURCE}".username oauth
    #     git config credential."${MIGRATION_SOURCE}".password '${{ secrets.MIGRATION_GL_TOKEN }}'
    #    elif [[ -n "${STARTEAM_URL_BASE}" ]]; then
    #     printf "\e[0;33m%s\e[0m\n" "Adding remote for StarTeam with URL ${STARTEAM_URL_BASE}"
    #     git remote add bitbucket "${STARTEAM_URL_BASE}"
    #    elif [[ -n "${BB_REPO_URL}" ]]; then
    #     printf "\e[0;33m%s\e[0m\n" "Adding remote for Bitbucket with URL ${BB_REPO_URL}"
    #     git remote add bitbucket "${BB_REPO_URL}"
    # 
    #    fi
#
    #- name: Sincronizar com StarTeam e Push para Bitbucket
    #  id: sync_starteam_to_git
    #  env:
    #    STARTEAM_URL_BASE: starteam://teste1:Adtes:mz-cw-ap-984.corp.bra.com.br:49201/TES/Hexa_TES
    #    BITBUCKET_REPO_URL: https://${{ vars.MIGRATION_BB_USER }}:${{ secrets.MIGRATION_BB_PASSWORD }}@bitbucket.bradesco.com.br:8443/scm/${{ steps.inputs.outputs.PROJECT_KEY }}/${{ steps.inputs.outputs.BITBUCKET_REPOSITORY }}.git
    #  run: |
    #    echo "::group::Iniciando sincronização com StarTeam"
    #    
    #    # Sincronizar StarTeam para um repositório Git local
    #    if [[ -n "${STARTEAM_URL_BASE}" ]]; then
    #      printf "\e[0;33m%s\e[0m\n" "Sincronizando StarTeam para repositório Git local"
    #      git-starteam sync --source "${STARTEAM_URL_BASE}" --destination "./local_git_repo"
    #      cd ./local_git_repo
    #      
    #      # Adicionar Bitbucket como remoto
    #      printf "\e[0;33m%s\e[0m\n" "Adicionando remoto para Bitbucket com URL ${BITBUCKET_REPO_URL}"
    #      git remote add bitbucket "${BITBUCKET_REPO_URL}"
    #      
    #      # Fazer o push para o Bitbucket
    #      printf "\e[0;33m%s\e[0m\n" "Enviando as alterações para o Bitbucket"
    #      git push bitbucket main  # substitua 'main' pelo nome da branch correta
    #    else
    #      echo "URL do StarTeam não foi especificado corretamente."
    #    fi
    # 