name: Clone Repository

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    clone-repo:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout this repository
          uses: actions/checkout@v2

        #- name: Install Git
        #  run: |
        #    sudo apt-get update
        #    sudo add-apt-repository ppa:git-core/ppa -y

        - name: Inicializar repositório Git e adicionar remoto Bitbucket
          run: |
            git init
            git remote add bitbucket "https://pusrstem:Adminstemgp93@mz-cw-ap-984.corp.bradesco.com.br:49201/STEM/Hexa_starteam.git"
            git fetch bitbucket
               